services:
  dashboard-ui:
    container_name: dashboard-ui
    image: drillview02.azurecr.io/drillview.dashboard:${BUILD_NUMBER}
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      BUILD_NUMBER: ${BUILD_NUMBER}
      HOST_NAME: ${HOST_NAME}
      SSL_ENABLED: ${SSL_ENABLED}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE}
      SSL_KEY: ${SSL_KEY}
      SECURED_IDENTITY_URL: ${SECURED_IDENTITY_URL}
      SERVICE_MANAGER_URL: ${SERVICE_MANAGER_URL}
      PRODUCT_STORE_URL: ${PRODUCT_STORE_URL}
      APP_DATA_STORE_URL: ${APP_DATA_STORE_URL}
      DATA_SIMPLEX_SERVICE_URL: ${DATA_SIMPLEX_SERVICE_URL}
      ADMIN_DB_ENDPOINT: ${ADMIN_DB_ENDPOINT}
      ADMIN_DB_NAME: ${ADMIN_DB_NAME}
      ADMIN_DB_USERNAME: ${ADMIN_DB_USERNAME}
      ADMIN_DB_PASSWORD: ${ADMIN_DB_PASSWORD}
      TRACE_DB_ENDPOINT: ${TRACE_DB_ENDPOINT}
      TRACE_DB_NAME: ${TRACE_DB_NAME}
      TRACE_DB_USERNAME: ${TRACE_DB_USERNAME}
      TRACE_DB_PASSWORD: ${TRACE_DB_PASSWORD}
      CHAT_DB_ENDPOINT: ${CHAT_DB_ENDPOINT}
      CHAT_DB_NAME: ${CHAT_DB_NAME}
      CHAT_DB_USERNAME: ${CHAT_DB_USERNAME}
      CHAT_DB_PASSWORD: ${CHAT_DB_PASSWORD}
      DASHBOARD_DB_ENDPOINT: ${DASHBOARD_DB_ENDPOINT}
      DASHBOARD_DB_NAME: ${DASHBOARD_DB_NAME}
      DASHBOARD_DB_USERNAME: ${DASHBOARD_DB_USERNAME}
      DASHBOARD_DB_PASSWORD: ${DASHBOARD_DB_PASSWORD}
      DATACOLLECT_DB_ENDPOINT: ${DATACOLLECT_DB_ENDPOINT}
      DATACOLLECT_DB_NAME: ${DATACOLLECT_DB_NAME}
      DATACOLLECT_DB_USERNAME: ${DATACOLLECT_DB_USERNAME}
      DATACOLLECT_DB_PASSWORD: ${DATACOLLECT_DB_PASSWORD}
      SYNCHRONIZER_DB_ENDPOINT: ${SYNCHRONIZER_DB_ENDPOINT}
      SYNCHRONIZER_DB_NAME: ${SYNCHRONIZER_DB_NAME}
      SYNCHRONIZER_DB_USERNAME: ${SYNCHRONIZER_DB_USERNAME}
      SYNCHRONIZER_DB_PASSWORD: ${SYNCHRONIZER_DB_PASSWORD}
      UNIT_DB_ENDPOINT: ${UNIT_DB_ENDPOINT}
      UNIT_DB_NAME: ${UNIT_DB_NAME}
      UNIT_DB_USERNAME: ${UNIT_DB_USERNAME}
      UNIT_DB_PASSWORD: ${UNIT_DB_PASSWORD}
      MIN_TRACE_LEVEL: ${MIN_TRACE_LEVEL}
      APP_USER_INACTIVE_DURATION: ${APP_USER_INACTIVE_DURATION}
      APP_API_BASE_URL: /api
    volumes:
      - ./storage/dashboardicons:/dashboardapp/public/uploads/dashboardicon
      - ./storage/ChatMediaStorage:/dashboardapp/public/uploads/chat