import { JobConfig, WITSMLVersion } from '../../server/interfaces/synchronizer.interfaces';

export const SynchronizerSaveData: JobConfig = {
  JobUID: '',
  JobName: '',
  LastUpdatedUser: '',
  JobStatus: 0,
  CreationDate: 0,
  LastUpdatedDate: 0,
  Settings: {
    StartDateIndexInUtc: 0,
    StartIndexInft: 0,
    BackFilling: false,
    HeaderFrequencyInMinute: 0,
    DataFrequencyInSecond: 0,
  },
  Source: {
    MaxConnections: 0,
    Url: '',
    UserName: '',
    Password: '',
    Version: WITSMLVersion.v1,
    Proxy: {
      UseProxy: false,
      HostName: '',
      Authentication: false,
      UserName: '',
      Password: '',
    },
  },
  Target: {
    ProductStore: {
      Url: '',
      UserName: '',
      Password: '',
      UserType: '',
      Proxy: {
        UseProxy: false,
        HostName: '',
        Authentication: false,
        UserName: '',
        Password: '',
      },
    },
    DataStore: {
      Url: '',
      UserName: '',
      Password: '',
      UserType: '',
      Proxy: {
        UseProxy: false,
        HostName: '',
        Authentication: false,
        UserName: '',
        Password: '',
      },
    },
  },
  Wellbores: [
    {
      Source: {
        UidWell: '',
        UidWellbore: '',
        NameWell: '',
        NameWellbore: '',
      },
      Target: {
        SameAsSource: false,
        UidWell: '',
        UidWellbore: '',
        NameWell: '',
        NameWellbore: '',
      },
    },
  ],
  Transfer: {
    AllTimeLogs: false,
    AllDepthLogs: false,
    AllTrajectries: false,
    AllMudLogs: false,
    AllRigs: false,
    AllBhaRun: false,
    AllCementJob: false,
    AllFluidsReport: false,
    AllFormationMarker: false,
    AllMessage: false,
    AllTubular: false,
    AllWbGeometry: false,
  },
  TimebaseLogs: [],
  DepthLogs: [],
  Trajectories: [],
  MudLogs: [],
  Rigs: [],
  BHARun: [],
  FluidReport: [],
  WbGeometries: [],
};
