import { IRigTemplate } from '../../../interfaces/datacollection.interfaces';

const Records: IRigTemplate[] = [
  {
    Name: 'MUD',
    Records: [
      {
        RecordId: 1,
        Name: 'General Time-Based',
        TimeLogUid: '97989583-9022-4e12-9ada-091fc97e8a6c',
        DepthLogUid: '1e1b6b2d-d4c9-4887-875e-586c057ae786',
        Description: 'Drilling data gathered at regular time intervals',
        TargetName: 'General Time-Based',
        TimeBased: true,
        DepthBased: false,
        DepthIncreasing: true,
        Enabled: true,
        Items: [
          {
            Uuid: 'e27da685-da34-4b4c-8787-2bbc4b2fb760',
            ItemId: 1,
            Description: 'Well Identifier',
            LongMnemonic: 'WELLID',
            ShortMnemonic: 'WID',
            TargetName: 'WID',
            Type: 'A',
            Length: 11,
            UnitType: null,
            Enabled: true,
            SourceUnit: null,
          },
          {
            Uuid: '7413dec5-d0f7-45f3-b09d-4213391ce8b5',
            ItemId: 2,
            Description: 'Sidetrack/Hole Sect No.',
            LongMnemonic: 'STKNUM',
            ShortMnemonic: 'SKNO',
            TargetName: 'SKNO',
            Type: 'S',
            Length: 2,
            UnitType: null,
            Enabled: false,
            SourceUnit: null,
          },
        ],
      },
      {
        RecordId: 2,
        Name: 'Drilling - Depth Based',
        TimeLogUid: '0CB9E0CF-4934-9F2C-8602-B8947BB08C6F',
        DepthLogUid: 'AD2439DC-9094-9D51-7742-ACEA3DD78687',
        Description: 'Drilling data gathered at regular depth intervals',
        TargetName: 'Drilling - Depth Based',
        Enabled: true,
        TimeBased: true,
        DepthBased: false,
        DepthIncreasing: true,
        Items: [
          {
            Uuid: 'e27da685-da34-4b4c-8787-2bbc4b2fb760',
            ItemId: 1,
            Description: 'Well Identifier',
            LongMnemonic: 'WELLID',
            ShortMnemonic: 'WID',
            TargetName: 'WID',
            Type: 'A',
            Length: 16,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
          {
            Uuid: '7413dec5-d0f7-45f3-b09d-4213391ce8b5',
            ItemId: 2,
            Description: 'Sidetrack/Hole Sect No.',
            LongMnemonic: 'STKNUM',
            ShortMnemonic: 'SKNO',
            TargetName: 'SKNO',
            Type: 'S',
            Length: 2,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
        ],
      },
      {
        RecordId: 3,
        Name: 'Drilling - Connections',
        TimeLogUid: '98989583-9022-4e12-9ada-091fc97e8a7c',
        DepthLogUid: '2e1b6b2d-d4c9-4887-875e-586c057ae786',
        Description: 'Data gathered at drilling connections',
        TargetName: 'Drilling - Connections',
        Enabled: true,
        TimeBased: true,
        DepthBased: false,
        DepthIncreasing: true,
        Items: [
          {
            Uuid: 'e27da685-da34-4b4c-8787-2bbc4b2fb760',
            ItemId: 1,
            Description: 'Well Identifier',
            LongMnemonic: 'WELLID',
            ShortMnemonic: 'WID',
            TargetName: 'WID',
            Type: 'A',
            Length: 15,
            UnitType: null,
            Enabled: true,
            SourceUnit: null,
          },
          {
            Uuid: 'e27da685-da34-4b4c-8787-2bbc4b2fb760',
            ItemId: 2,
            Description: 'Time',
            LongMnemonic: 'Time',
            ShortMnemonic: 'Time',
            TargetName: 'Time',
            Type: 'A',
            Length: 15,
            UnitType: null,
            Enabled: true,
            SourceUnit: null,
          },
        ],
      },
    ],
  },
  {
    Name: 'MWD',
    Records: [
      {
        RecordId: 1,
        Name: 'Drilling - Depth Based',
        TimeLogUid: 'b0b1106c-f4e2-4d76-b2af-a642d216d452',
        DepthLogUid: '9030bb5f-ffb7-40c1-bfc4-1db98356debb',
        Description: 'Drilling data gathered at regular depth intervals',
        TargetName: 'Drilling - Depth Based',
        TimeBased: true,
        DepthBased: false,
        DepthIncreasing: true,
        Enabled: true,
        Items: [
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 1,
            Description: 'Well Identifier',
            LongMnemonic: 'WELLID',
            ShortMnemonic: 'WID',
            TargetName: 'WID',
            Type: 'A',
            Length: 16,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 2,
            Description: 'Sidetrack/Hole Sect No.',
            LongMnemonic: 'STKNUM',
            ShortMnemonic: 'SKNO',
            TargetName: 'SKNO',
            Type: 'S',
            Length: 15,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
        ],
      },
    ],
  },
  {
    Name: 'MWDL',
    Records: [
      {
        RecordId: 1,
        Name: 'General Time-Based',
        TimeLogUid: '3fc4fa99-42f2-4977-b170-e348b1a67dca',
        DepthLogUid: '6603017b-bc55-4904-a6f3-10b4529f682f',
        Description: 'Drilling data gathered at regular time intervals',
        TargetName: 'General Time-Based',
        TimeBased: true,
        DepthBased: false,
        DepthIncreasing: true,
        Enabled: true,
        Items: [
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 1,
            Description: 'Well Identifier',
            LongMnemonic: 'WELLID',
            ShortMnemonic: 'WID',
            TargetName: 'WID',
            Type: 'A',
            Length: 16,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 2,
            Description: 'Sidetrack/Hole Sect No.',
            LongMnemonic: 'STKNUM',
            ShortMnemonic: 'SKNO',
            TargetName: 'SKNO',
            Type: 'S',
            Length: 2,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 3,
            Description: 'Record Identifier',
            LongMnemonic: 'RECID',
            ShortMnemonic: 'RID',
            TargetName: 'RID',
            Type: 'S',
            Length: 2,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
        ],
      },
    ],
  },
  {
    Name: 'DAS',
    Records: [
      {
        RecordId: 1,
        Name: 'Hydraulics',
        TimeLogUid: '628F0A33-4161-39F3-6C1A-5629C28D6EB1',
        DepthLogUid: '677E44C5-A470-3F30-1647-0C4B4260384E',
        Description: 'Hydraulics data gathered while circulating',
        TargetName: 'Hydraulics',
        TimeBased: true,
        DepthBased: true,
        DepthIncreasing: false,
        Enabled: true,
        Items: [
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 1,
            Description: 'Well Identifier',
            LongMnemonic: 'WELLID',
            ShortMnemonic: 'WID',
            TargetName: 'WID',
            Type: 'A',
            Length: 16,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 2,
            Description: 'Sidetrack/Hole Sect No.',
            LongMnemonic: 'STKNUM',
            ShortMnemonic: 'SKNO',
            TargetName: 'SKNO',
            Type: 'S',
            Length: 2,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
          {
            Uuid: '00000000-0000-0000-0000-000000000000',
            ItemId: 3,
            Description: 'Record Identifier',
            LongMnemonic: 'RECID',
            ShortMnemonic: 'RID',
            TargetName: 'RID',
            Type: 'S',
            Length: 2,
            Enabled: true,
            UnitType: null,
            SourceUnit: null,
          },
        ],
      },
    ],
  },
];

export default Records;
